### ISSUE TITLE
Playback speed is faster for some audios

### ISSUE THREAD

**Issue by bkhall** [brianwernick/ExoMedia#148]
https://github.com/google/ExoPlayer/issues/801

I know this against ExoPlayer library. but it seems to be a simple fix. Could you pick it up and issue a patch?

- [X] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `2.5.5`
 - Device OS version: `4.x.x`
 - Devide Manufacturer: `All`
 - Device Name: `All`
 
###### Reproduction Steps
Play any mono feed

###### Expected Result
Playback at normal rate

###### Actual Result
Playback at very high rate

**Comment by se-bastiaan** [comment]
The next version of ExoMedia will contain this fix. It was fixed in ExoPlayer 1.5.6 and the source was updated to that version 23 days ago (https://github.com/brianwernick/ExoMedia/commit/831684c1ec8d4d4ce228446d3cf8eaa5ae839c1e). The last ExoMedia release was 29 days ago (https://github.com/brianwernick/ExoMedia/commit/e3920cb3a35796406bd81725f5f8fd1bc8c434f8)

**Comment by bkhall** [comment]
OK, close this ticket then, because we are still seeing it in 2.5.5. I will log new comments against the ExoPlayer ticket.

**Comment by bkhall** [comment]
Ok, how far out from releasing are you?

**Comment by brianwernick** [comment]
I'll try to get a patch out this week, there are a few bugs that I've been looking in to that I want to get in to the patch

**Comment by brianwernick** [comment]
`2.5.6` has been released

**Comment by httpdispatch** [comment]
I've experienced same issue playing 48kHz Stereo AAC-LC VBR files at some samsung phones using ExoMedia 3.0.4. The problem is that issue is not constant. Sometimes file plays correctly, sometimes it plays at 20x speed (Checking via getCurrentPosition). Is there any known workarounds for this? Maybe different encoding settigns?
